version: '3.8'

services:
  mongodb:
    image: mongo:7.0
    container_name: taskhub-mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    networks:
      - taskhub-network

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: taskhub-backend
    ports:
      - "5000:5000"
    environment:
      - MONGODB_URI=mongodb://mongodb:27017/taskhub
      - PORT=5000
      - NODE_ENV=production
    depends_on:
      - mongodb
    networks:
      - taskhub-network
    restart: unless-stopped

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: taskhub-frontend
    ports:
      - "3000:80"
    environment:
      - REACT_APP_API_URL=
    depends_on:
      - backend
    networks:
      - taskhub-network
    restart: unless-stopped

networks:
  taskhub-network:
    driver: bridge

volumes:
  mongodb_data:
